# Generated by Django 5.2.14 on 2026-05-27 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('activity_type', models.CharField(max_length=255)),
                ('activity_start_date', models.DateField()),
                ('activity_end_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('source_system', models.CharField(max_length=100)),
                ('raw_record_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('system_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_emissions_records', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissions_status_changes', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='emissions.normalizedemissionsdata')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['emission_record', 'changed_at'], name='emissions_a_emissio_7891d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedemissionsdata',
            index=models.Index(fields=['tenant', 'status'], name='emissions_n_tenant__066c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionsdata',
            index=models.Index(fields=['tenant', 'scope_category'], name='emissions_n_tenant__8978ea_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionsdata',
            index=models.Index(fields=['source_system', 'raw_record_id'], name='emissions_n_source__497304_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionsdata',
            index=models.Index(fields=['activity_start_date', 'activity_end_date'], name='emissions_n_activit_18a973_idx'),
        ),
        migrations.AddConstraint(
            model_name='normalizedemissionsdata',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_system', 'raw_record_id'), name='unique_source_record_per_tenant'),
        ),
    ]
